# Generated by Django 5.2.15 on 2026-07-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0002_topic_studied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSchedule',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='topics.topic')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'constraints': [models.UniqueConstraint(fields=('topic', 'revision_number'), name='unique_revision_number_per_topic')],
            },
        ),
    ]
