# Generated by Django 5.2.15 on 2026-07-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='studied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
