# Generated by Django 5.2.15 on 2026-07-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_message_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
