# Generated by Django 5.2.15 on 2026-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_remove_conversation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='faiss_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
